version: '3.8'

services:
  db1:
    image: postgres:15
    container_name: database_1
    restart: always
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: db1
    ports:
      - "5432:5432"
    volumes:
      - db1_data:/var/lib/postgresql/data
      - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql

  db2:
    image: postgres:15
    container_name: database_2
    restart: always
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: db2
    ports:
      - "5433:5432"
    volumes:
      - db2_data:/var/lib/postgresql/data

volumes:
  db1_data:
  db2_data:
